# Generated by Django 2.2.3 on 2019-12-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computadora',
            old_name='sistema',
            new_name='sistemaoperativo',
        ),
        migrations.RenameField(
            model_name='sistemaoperativo',
            old_name='sistema',
            new_name='sistemaoperativo',
        ),
    ]
