# Generated by Django 2.2.3 on 2020-01-15 01:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191226_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='AireDatacenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codaire', models.CharField(max_length=4)),
                ('nombreaire', models.CharField(max_length=50)),
                ('modeloaire', models.CharField(max_length=50)),
                ('marcaaire', models.CharField(max_length=50)),
                ('serieaire', models.CharField(max_length=50)),
                ('nombrecondensadoraaire', models.CharField(max_length=50)),
                ('modelocondensadoraaire', models.CharField(max_length=50)),
                ('seriecondensadoraaire', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmaSistemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmacontraincendio', models.CharField(max_length=4)),
                ('alarmacontraincendiohabilitado', models.CharField(max_length=4)),
                ('cilindroprincipallleno', models.CharField(max_length=4)),
                ('cilindromanual', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codats', models.CharField(max_length=4)),
                ('nombreats', models.CharField(max_length=50)),
                ('modeloats', models.CharField(max_length=50)),
                ('marcaats', models.CharField(max_length=50)),
                ('serieats', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmaaire', models.CharField(max_length=4)),
                ('aireencendido', models.CharField(max_length=4)),
                ('horaaire', models.CharField(max_length=4)),
                ('temperaturaaire', models.CharField(max_length=15)),
                ('humedadaire', models.CharField(max_length=15)),
                ('aire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.AireDatacenter')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lucesencendidasayb', models.CharField(max_length=4)),
                ('preferencia', models.CharField(max_length=4)),
                ('amps', models.CharField(max_length=4)),
                ('aire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.AireDatacenter')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleLectUps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmaups', models.CharField(max_length=4)),
                ('bateriaups', models.CharField(max_length=4)),
                ('cargaups', models.CharField(max_length=4)),
                ('ventups', models.CharField(max_length=4)),
                ('vsalups', models.CharField(max_length=4)),
                ('hertzups', models.CharField(max_length=4)),
                ('czasups', models.CharField(max_length=4)),
                ('prhorasups', models.CharField(max_length=4)),
                ('prminutosups', models.CharField(max_length=4)),
                ('aire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.AireDatacenter')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codequipo', models.CharField(max_length=15)),
                ('fechacompra', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('observacion', models.CharField(max_length=100)),
                ('diagnosticada', models.CharField(max_length=60)),
                ('discoduro', models.CharField(max_length=60)),
                ('servicetag', models.CharField(max_length=60)),
                ('direccionip', models.CharField(max_length=60)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechamantenimiento', models.CharField(max_length=100)),
                ('realizado', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaprotocolo', models.CharField(max_length=17)),
                ('historialeventos', models.CharField(max_length=20)),
                ('tenperaturadata', models.CharField(max_length=5)),
                ('humedadaire', models.CharField(max_length=5)),
                ('revisionequipos', models.CharField(max_length=200)),
                ('observaciones', models.CharField(max_length=200)),
                ('panelregulado', models.CharField(max_length=5)),
                ('panelnoregulado', models.CharField(max_length=5)),
                ('ventosasenposicion', models.CharField(max_length=5)),
                ('boquillaaerea', models.CharField(max_length=5)),
                ('boquillabajopiso', models.CharField(max_length=5)),
                ('lucesprincipalesbuenestado', models.CharField(max_length=5)),
                ('camarafuncionando', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codups', models.CharField(max_length=4)),
                ('nombreups', models.CharField(max_length=50)),
                ('modeloups', models.CharField(max_length=50)),
                ('marcaups', models.CharField(max_length=50)),
                ('serieups', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='auditoria',
            old_name='accion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='lugarreparacion',
            old_name='lugar',
            new_name='lugarreparacion',
        ),
        migrations.RenameField(
            model_name='oficina',
            old_name='oficina',
            new_name='codoficina',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='codusuario',
        ),
        migrations.RemoveField(
            model_name='oficina',
            name='departamento',
        ),
        migrations.AddField(
            model_name='departamento',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Oficina'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombreusuario',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Computadora',
        ),
        migrations.AddField(
            model_name='protocolo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Usuario'),
        ),
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Oficina'),
        ),
        migrations.AddField(
            model_name='mantenimientopreventivo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Usuario'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='lugarreparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.LugarReparacion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Modelo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Oficina'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Usuario'),
        ),
        migrations.AddField(
            model_name='detallelectups',
            name='protocolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Protocolo'),
        ),
        migrations.AddField(
            model_name='detalleats',
            name='protocolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Protocolo'),
        ),
        migrations.AddField(
            model_name='detalleaire',
            name='protocolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Protocolo'),
        ),
        migrations.AddField(
            model_name='alarmasistemas',
            name='protocolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Protocolo'),
        ),
        migrations.AddField(
            model_name='procesador',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Equipo'),
        ),
        migrations.AddField(
            model_name='sistemaoperativo',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Equipo'),
        ),
    ]
