# Generated by Django 2.2.3 on 2020-01-15 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200114_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='oficina',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
