# Generated by Django 2.2.3 on 2020-01-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_oficina_oficina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolo',
            old_name='humedadaire',
            new_name='humedaddata',
        ),
        migrations.RenameField(
            model_name='protocolo',
            old_name='tenperaturadata',
            new_name='temperaturadata',
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='codoficina',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='oficina',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='procesador',
            field=models.CharField(max_length=150),
        ),
    ]
