# Generated by Django 2.2.3 on 2020-03-17 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200128_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleats',
            old_name='Ats',
            new_name='ats',
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombreequipo',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airedatacenter',
            name='codaire',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ats',
            name='codats',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ups',
            name='codups',
            field=models.CharField(max_length=10),
        ),
    ]
