# Generated by Django 2.2.3 on 2020-03-22 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200317_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='oaverde',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolo',
            name='ocverde',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
